2025-03-24 18:28:04,457 - INFO - Starting...
2025-03-24 18:28:04,457 - INFO - Start polling
2025-03-24 18:28:04,458 - INFO - Running truck synchronization...
2025-03-24 18:28:04,459 - INFO - Running sending auto notifications....
2025-03-24 18:28:04,685 - INFO - Polling stopped
2025-03-24 18:28:05,054 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<run_fastapi() done, defined at C:\Users\shohj\PycharmProjects\truck\src\main.py:66> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "C:\Users\shohj\PycharmProjects\truck\src\main.py", line 85, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\shohj\PycharmProjects\truck\src\main.py", line 69, in run_fastapi
    await server.serve()
  File "C:\Users\shohj\PycharmProjects\truck\venv\lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\shohj\PycharmProjects\truck\venv\lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
